initial commit
nalkhovikleverx/GoEdu pull request #17
Opened 2024-06-01 15:58 UTC by aliaksei-kosyrau-leverx

2024-06-13 13:54 UTC, nalkhovikleverx commented
The implementation should be moved from api to `internal/interfaces/inprocess` package. The api package should store just contracts, not an implementation.

2024-06-13 14:07 UTC, nalkhovikleverx requested changes

2024-06-13 14:07 UTC, nalkhovikleverx commented on internal/registration/api/inprocess/registration/registration.go
> +func CreateNewInProcessRegistrationModuleFacade() *RegistrationModuleFacade {
You should create a `module.go` inside `GoEdu/internal/registration` package and build all the module dependencies in there for now. The example is in `GoEdu/internal/api/http` module.

2024-06-17 15:34 UTC, nalkhovikleverx requested changes

2024-06-17 15:34 UTC, nalkhovikleverx commented on internal/registration/internal/infrastructure/inprocess/repository/memory/repository.go
> +		temp = append(temp, *domain.MustCreateUserRegistrationFromSnapshot(val))
return Snapshot

2024-06-24 11:43 UTC, forgoty requested changes

2024-06-24 11:43 UTC, forgoty commented on internal/api/http/controller/registration.go
> +	err := json.NewDecoder(r.Body).Decode(&cmd)
in `server.gen.go` there is `NewRegistration` request body struct. Please decode the json body into this struct and then map the `RegisterNewUserCommand` manually.

2024-06-24 11:43 UTC, forgoty commented on internal/registration/api/inprocess/interface.go
> +	FirstName string `json:"firstName"`
remove `json` struct tags from this struct. All consumers of this API for now should map it manualy.

2024-06-24 12:32 UTC, nalkhovikleverx requested changes

2024-06-25 08:08 UTC, nalkhovikleverx requested changes

2024-06-25 08:08 UTC, nalkhovikleverx commented on internal/api/http/controller/mapper.go
> +		Email:     string(registration.Email),
`Password` field not mapped.

2024-06-25 16:07 UTC, nalkhovikleverx approved these changes

2024-06-25 16:08 UTC, merged